" Load Plugins {{{
" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

Plug 'Valloric/YouCompleteMe'
" You should install flake8 or pylint for syntastic
Plug 'scrooloose/syntastic'
Plug 'fatih/vim-go'
Plug 'fvdnabee/a.vim'
Plug 'mileszs/ack.vim'
Plug 'kien/ctrlp.vim'
Plug 'Lokaltog/vim-easymotion'
Plug 'scrooloose/nerdtree'
Plug 'jistr/vim-nerdtree-tabs'
Plug 'dkprice/vim-easygrep'
" vim airline, note that you will need a patched powerline font for this, see
" http://vi.stackexchange.com/a/3363
Plug 'vim-airline/vim-airline'
" Tagbar, class outline viewer:
Plug 'majutsushi/tagbar'
" git integration in vim:
Plug 'tpope/vim-fugitive'
" better JSON syntax highlighting:
Plug 'elzr/vim-json'
" save vim sessions:
Plug 'tpope/vim-obsession'
Plug 'vim-python/python-syntax'
Plug 'tell-k/vim-autopep8'

" themes:
" wombat256mod colour scheme for vim:
Plug 'vim-scripts/wombat256.vim'
" Solarized colour scheme for vim:
Plug 'altercation/vim-colors-solarized'
" Base16 colour scheme for vim:
" Plug 'chriskempson/base16-vim'
" Gruvbox
Plug 'morhetz/gruvbox'

" Initialize plugin system
call plug#end()
" }}}
" Whitespace, color and fonts {{{
" Show whitespace
" MUST be inserted BEFORE the colorscheme command
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=white guibg=white
au InsertLeave * match ExtraWhitespace /\s\+$/

" Color schemes
" 1) wombat256mod
" mkdir -p ~/.vim/colors && cd ~/.vim/colors
" wget -O wombat256mod.vim http://www.vim.org/scripts/download_script.php?src_id=13400
" set t_Co=256
" colorscheme wombat256mod
" 2) solarized:
" let g:solarized_termcolors=256
" set t_Co=256
" set background=dark
" colorscheme solarized
" 3) base16:
" let base16colorspace=256
" set background=dark
" colorscheme base16-colors
" 4) gruvbox:
set termguicolors
let g:gruvbox_italic=1
let g:gruvbox_contrast_dark='high'
set background=dark    " Setting dark mode
colorscheme gruvbox

" Font for gvim:
set guifont=DejaVu\ Sans\ Mono\ for\ Powerline\ 10

" }}}
" UI Layout {{{
set cursorline	" Highlight current line
set showmatch	" higlight matching parenthesis
set tw=79	" width of document (used by gd)
set nowrap	" don't automatically wrap on load
set fo-=t	" don't automatically wrap text when typing
set scrolloff=3 " lines of text around cursor

set showcmd	" show command in bottom bar
set wildmenu	" show command-line completion matches just above the command line

set hidden 	" don't ask for confirmation for hidden buffers
" Colour column 80
set colorcolumn=80
highlight ColorColumn ctermbg=233

" }}}
" Relative/absolute line numbers {{{
" Showing line numbers, the following two lines will always show the absolute
" line number for the cursor line and the surrounding lines will show the
" relative line number
set number	" show line numbers
set relativenumber " show relative line numbers, easy for moving around with j/k

" function to toggle between abs and rel line numbers
function! RelativeNumberToggle()
  if(&relativenumber == 1)
    set norelativenumber
  else
    set relativenumber
  endif
endfunc

nnoremap <C-n> :call RelativeNumberToggle()<cr>

" }}}
" Searching {{{
set incsearch           " search as characters are entered
set hlsearch            " highlight matches
set ignorecase 		" case-insensitive search (but also see next option)
set smartcase		" make search case insensitive when no upper case letters are found in the search pattern
" }}}
" Spaces & Tabs {{{
" Enable filetype detection, indentation and syntax highlighting
filetype plugin on
filetype indent on
syntax on

" Set foldingmethod to syntax, note this requires a syntax file for every language in syntax
set foldmethod=syntax

nnoremap <space> za	" space open/closes folds

set tabpagemax=30 	" Increase number of tabs
set modelines=1		" Search the last line of a file for file-specific vimrc modes

" easier moving of code blocks
" Try to go into visual mode (v), thenselect several lines of code here and
" then press ``>`` several times.
vnoremap < <gv " better indentation
vnoremap > >gv " better indentation
" }}}
" Leader {{{
" Rebind <Leader> key
" I like to have it here becuase it is easier to reach than the default and
" it is next to ``m`` and ``n`` which I use for navigating between tabs.
let mapleader = ","

" easier moving between tabs
"map <Leader>n <esc>:tabprevious<CR>
"map <Leader>m <esc>:tabnext<CR>

" Easier navigation between buffers:
map <Leader>m :bn<cr>
map <Leader>n :bp<cr>
"map <Leader>d :bd<cr>
map <Leader>d :bp\|bd #<cr>
nnoremap <F5> :buffers<CR>:buffer<Space>

" open new tab with <Leader>T
map <Leader>T <esc>:tabnew<CR>

" turn off search highlight
nnoremap <leader><space> :nohlsearch<CR>

" Rebind tag next
map <Leader>b <esc>:tn<CR>
map <Leader>v <esc>:tp<CR>
" }}}
" Quick save/quit {{{
" Quicksave command
noremap <C-s> :update<CR>
vnoremap <C-s> <C-C>:update<CR>
inoremap <C-s> <C-O>:update<CR>

" Quick quit command
noremap <Leader>e :quit<CR>	" Quit current window
noremap <Leader>E :qa!<CR> 	" Quit all windows

" Quick quick+save command
noremap <Leader>x :x<CR> 	" Quit and save current window
" }}}
" Misc key mappings {{{
" bind Ctrl+<movement> keys to move around the windows, instead of using Ctrl+w + <movement>
" Every unnecessary keystroke that can be saved is good for your health :)
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

" Goto the next/previous error in source code remapping or search match
map cn <esc>:cn<cr>
map cp <esc>:cp<cr>
nmap <silent> <RIGHT> :cnext<CR>
nmap <silent> <LEFT> :cprev<CR>

" scroll the viewport faster
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

" highlight last inserted text
nnoremap gV `[v`]

" jk is escape
inoremap jk <esc>

" easier formatting of paragraphs (for text input)
vmap Q gq
nmap Q gqap
" }}}
" Misc {{{
set ttyfast	" faster redraw
" Useful settings
set history=700
set undolevels=700
" Mouse and backspace
set mouse=a	" enable mouse (on OSX press ALT and click)
set backspace=2	" make backspace behave like normal again
" Custom C function colors
"hi cCustomFunc  gui=bold guifg=yellowgreen
"hi cCustomClass gui=reverse guifg=#00FF00

" Ignore specific files/directories:
:set wildignore+=*.o,*.d,.git,.svn,*/doxygen-html/*,*/userlevel/*

" Automatic reloading of .vimrc
" autocmd! bufwritepost .vimrc source %

" Better copy & paste
" When you want to paste large blocks of code into vim, press F2 before you
" paste. At the bottom you should see ``-- INSERT (paste) --``.
set pastetoggle=<F2>
set clipboard=unnamed

" Automatically regenerate tag files
" autocmd BufWritePost *.cc,*.hh,*.c,*.h silent! !/usr/bin/ctags -R 2> /dev/null &
"set tags=./tags,./TAGS;$HOME " 1. tags, 2. TAGS, 3.… until $HOME
set tags=tags;/
" }}}
" CtrlP {{{
nmap <C-\> :CtrlPBuffer<CR>
nmap <C-m> :CtrlPMRU<CR>

let g:ctrlp_match_window = 'bottom,order:ttb,min:1,max:10,results:100'
let g:ctrlp_switch_buffer = 0
"let g:ctrlp_working_path_mode = 0
let g:ctrlp_cache_dir = $HOME . '/.cache/ctrlp'
" note ctrlp_custom_ignore does not work if you use a custom user command (like
" ag), see ctrlp_user_command in next section on how to ignore files with ah
let g:ctrlp_custom_ignore = '\v[\/](node_modules|target|dist|venv|env)|(\.(swp|ico|git|svn|pyc|egg))$'
" }}}
" The Silver Searcher (ag) {{{
" Urge Vim to use ag for :grep commands
if executable('ag')
	" Note we extract the column as well as the file and line number
	" set grepprg=ag\ --nogroup\ --nocolor\ --column
	" set grepformat=%f:%l:%c%m

	" Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
	" let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
	let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden
	      \ --ignore .git
	      \ --ignore .svn
	      \ --ignore .hg
	      \ --ignore .DS_Store
	      \ --ignore "**/*.pyc"
	      \ --ignore env
	      \ --ignore venv
	      \ -g ""'

	" ag is fast enough that CtrlP doesn't need to cache
	" let g:ctrlp_use_caching = 0

	" Specify the ack.vim plugin to use ag
	" The benefit of combining Ag with Ack is that Ack's Quickfix window has useful short cuts
	let g:ackprg = 'ag --nogroup --nocolor --column'
endif

" bind K to Ack word under cursor
nnoremap K :Ack!<CR>
" nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>
" }}}
" NERDTree {{{
" Start with NERDTree opened
" autocmd VimEnter waits until all initialization is finished (plugins are loaded)
" autocmd VimEnter * NERDTree
" autocmd VimEnter * wincmd p
" let g:nerdtree_tabs_open_on_console_startup=1
" NERDTree on right side
" let g:NERDTreeWinPos = "right"

" Toggle NERDTree accross all tabs:
nmap <F3> :NERDTreeTabsToggle<CR>
" autocmd VimEnter * NERDTreeTabsToggle
" }}}
" AutoGroups {{{
augroup configgroup
	autocmd!
	"autocmd FileType cc setlocal shiftwidth=2 tabstop=2 softtabstop=2 expandtab shiftround
	autocmd FileType c setlocal shiftwidth=2 tabstop=2 softtabstop=2 expandtab shiftround
	"autocmd FileType hh setlocal shiftwidth=2 tabstop=2 softtabstop=2 expandtab shiftround
	autocmd FileType h setlocal shiftwidth=2 tabstop=2

	autocmd FileType python setlocal foldmethod=indent
	autocmd FileType python setlocal shiftwidth=4
	autocmd FileType python setlocal tabstop=4
	autocmd FileType python setlocal softtabstop=4
	autocmd FileType python setlocal expandtab
	autocmd FileType python setlocal shiftround
	autocmd FileType python setlocal commentstring=#\ %s
	autocmd FileType python setlocal colorcolumn=160
	"autocmd FileType python setlocal equalprg=/usr/lib/python3.7/Tools/scripts/reindent.py
	autocmd FileType py setlocal filetype=python

	autocmd FileType html setlocal foldmethod=marker
	autocmd FileType html setlocal foldmarker={,}
	autocmd Filetype html setlocal tabstop=4
	autocmd FileType css setlocal foldmethod=syntax
	autocmd Filetype css setlocal tabstop=4
	autocmd FileType javascript setlocal foldmethod=marker
	autocmd FileType javascript setlocal foldmarker={,}
	autocmd Filetype javascript setlocal shiftwidth=4 tabstop=4 softtabstop=0

	autocmd FileType ruby setlocal tabstop=2
	autocmd FileType ruby setlocal shiftwidth=2
	autocmd FileType ruby setlocal expandtab
	autocmd FileType ruby setlocal softtabstop=2
	autocmd FileType ruby setlocal commentstring=#\ %s
	autocmd FileType ruby setlocal shiftround
	autocmd FileType rb setlocal filetype=ruby 

	autocmd FileType java setlocal noexpandtab
	autocmd FileType java setlocal list
	autocmd FileType java setlocal listchars=tab:+\ ,eol:-
	autocmd FileType java setlocal formatprg=par\ -w80\ -T4

	autocmd FileType matlab setlocal tabstop=4
	autocmd FileType matlab setlocal expandtab
	autocmd FileType matlab setlocal shiftwidth=4

	autocmd BufEnter *.click set filetype=click
	autocmd BufEnter *.conf set filetype=click
	autocmd BufEnter *.cfg set filetype=click

	autocmd BufEnter Makefile setlocal noexpandtab

	autocmd BufEnter *.sh setlocal tabstop=2
	autocmd BufEnter *.sh setlocal shiftwidth=2
	autocmd BufEnter *.sh setlocal softtabstop=2

	" add yaml stuffs
	autocmd FileType yaml,yml setlocal ts=2 sts=2 sw=2 expandtab
augroup END
" }}}
" Misc plugins {{{
" Use clang autocomplete
" let g:clang_use_library = 1

" Alternate header definition
" let g:alternateExtensions_CC = "hh"
" let g:alternateExtensions_HH = "cc"
let g:alternateSearchPath = 'sfr:../source,sfr:../src,sfr:../include,sfr:../inc,sfr:../../include,sfr:./include'

" Tagbar
nmap <F4> :TagbarToggle<CR>
" }}}
" Easygrep {{{
let g:EasyGrepCommand=1
let g:EasyGrepMode=2
let g:EasyGrepRecursive=1
let g:EasyGrepIgnoreCase=1
let g:EasyGrepJumpToMatch=0
" }}}
" YouCompleteMe {{{
let g:ycm_extra_conf_globlist = ['~/GIT/COAPClientGateway/*','!~/*']
let g:ycm_server_use_vim_stdout = 0
let g:ycm_server_log_level = 'debug'
" let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_autoclose_preview_window_after_insertion = 1
nnoremap <F6> :YcmForceCompileAndDiagnostics<CR>
nnoremap <F7> :YcmDiags<CR>
nnoremap <leader>g :YcmCompleter GoTo<CR>
nnoremap <leader>h :YcmCompleter GoToReferences<CR>
nnoremap <leader>j :YcmCompleter GetType<CR>
nnoremap <leader>k :YcmCompleter GetDoc<CR>

" }}}
" python-syntax {{{
let g:python_highlight_all = 1
" }}}
" syntastic (mainly for python) {{{
" Settings from https://github.com/vim-syntastic/syntastic/#settings
let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
" Other settings:
let g:syntastic_python_checkers = ['pylint', 'flake8'] " use both pylint and flake8
let g:syntastic_python_pylint_post_args = "--max-line-length=160"
let g:syntastic_python_flake8_args = "--max-line-length=160"
let g:syntastic_warning_symbol="⚠"
let g:syntastic_error_symbol="✗"
" let g:syntastic_python_python_exec = '/usr/bin/python3'
" Disable all style warnings
let g:syntastic_quiet_messages = {"type": "style"}
" }}}
" vim-go {{{
let g:go_doc_keywordprg_enabled = 0 " don't overwrite the mapping for the K key

" let g:go_fmt_autosave = 0 " work-around for go fmt losing vim folds, see https://github.com/fatih/vim-go/issues/502
" }}}
" gvim {{{
" Hide gvim toolbars:
:set guioptions-=T  "remove toolbar
:set guioptions-=r  "remove right-hand scroll bar
:set guioptions-=L  "remove left-hand scroll bar
:set guioptions-=b  "remove horizontal scroll bar

" Resize gvim window via Ctrl F12
" map <C-o> :set lines-=1 lines+=1<CR>

" How to make cut/copy/paste in GVim on Ubuntu work with Ctrl+X,Ctrl+C,Ctrl+V?
" http://superuser.com/a/189198/219425
vmap <C-c> "+yi
vmap <C-x> "+c
vmap <C-v> c<ESC>"+p
imap <C-v> <C-r><C-o>+
" }}}
" vim-airline {{{
" always show vim-airline:
set laststatus=2
" automatically populate the g:airline_symbols dictionary with the proper font glyphs for various symbols
let g:airline_powerline_fonts = 1
" Automatically displays all buffers when there's only one tab open.
let g:airline#extensions#tabline#enabled = 1
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"
" }}}
" Automatically set screen title
" http://vim.wikia.com/wiki/Automatically_set_screen_title
" let &titlestring = hostname() . "[vim(" . expand("%:t") . ")]"
" if &term == "screen"
"   set t_ts=^[k
"   set t_fs=^[\
" endif
" if &term == "screen" || &term == "xterm"
"   set title
" endif
set titlestring=%t%(\ %M%)%(\ (%{expand(\"%:p:h\")})%)%(\ %a%)\ -\ %{v:servername}
" vim:foldmethod=marker:foldlevel=0
