# Disable flow control, note should be placed before p10k instant prompt feature
stty -ixon

# https://github.com/romkatv/powerlevel10k#how-do-i-initialize-direnv-when-using-instant-prompt=
# To initialize direnv you need to add one line above that block and one line below it.
(( ${+commands[direnv]} )) && emulate zsh -c "$(direnv export zsh)"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Hook direnv into zsh
# https://direnv.net/docs/hook.html
# Must go under p10k instant prompt
(( ${+commands[direnv]} )) && emulate zsh -c "$(direnv hook zsh)"

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000000
SAVEHIST=1000000
setopt appendhistory share_history autocd beep extendedglob nomatch
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/fvdnabee/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
#

# Start of oh-my-zsh zshrc example:
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
# ZSH=/usr/share/oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# https://github.com/romkatv/powerlevel10k.git
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
ZSH_THEME="powerlevel10k/powerlevel10k"

# ZSH_THEME="robbyrussell"
# https://github.com/caiogondim/bullet-train.zsh
#
# AUR: https://aur.archlinux.org/packages/bullet-train-oh-my-zsh-theme-git/
# ZSH_THEME="bullet-train"
# Using powerlevel10k, see end of zshrc

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  cp
  virtualenv
  common-aliases
  vi-mode
  aws
  kubectl
  poetry  # Must save output of `poetry completions zsh` to $ZSH_CUSTOM/plugins/poetry/_poetry, see https://python-poetry.org/docs/#enable-tab-completion-for-bash-fish-or-zsh
  yarn-autocompletions  # https://github.com/g-plane/zsh-yarn-autocompletions
)

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# This does not appear to work with running sudoedit locally
# if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
# else
  # export EDITOR='mvim'
# fi

# Open visual mode in vim fullscreen
bindkey -M vicmd v edit-command-line

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias grep='grep --color=auto'
alias fgrep='fgrep --ignore-case -I -n --color=auto'
alias egrep='egrep --color=auto'
alias tmux='TERM=xterm-256color tmux'
alias gstuno='git status -uno'
source $HOME/.aliases

ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh
if [[ ! -d $ZSH_CACHE_DIR ]]; then
  mkdir $ZSH_CACHE_DIR
fi

source $ZSH/oh-my-zsh.sh
# End of oh-my-zsh zshrc example:

# Enable recursive search on Ctrl-R
bindkey '^R' history-incremental-search-backward
bindkey '^S' history-incremental-pattern-search-forward

# Keep track of directory in new tab
# https://unix.stackexchange.com/questions/93476/gnome-terminal-keep-track-of-directory-in-new-tab
. /etc/profile.d/vte-2.91.sh

# disable sharing history between zshs:
setopt nosharehistory

# Enable Home/End and Delete key
# bindkey "\033[1~" beginning-of-line
# bindkey "\033[4~" end-of-line
# bindkey "\033[3~" delete-char

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# https://github.com/romkatv/powerlevel10k.git
source /home/fvdnabee/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme
ZSH_THEME="powerlevel10k/powerlevel10k"
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Terraform autocomplete:
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/terraform terraform

# Setup gopath
# See https://stackoverflow.com/a/42616068/170154
export GOPATH=$HOME/go
export GOROOT=/usr/lib/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

# Enable GPG passphrase prompts from zsh
# See https://stackoverflow.com/a/55126554
# See also https://unix.stackexchange.com/a/608921 for how Powerlevel10k
# interference
export GPG_TTY=$TTY

# Switch from default find command to silver search in fzf in order to respect
# .gitignore, see https://github.com/junegunn/fzf#respecting-gitignore
# Note: this also affects fzf in vim
export FZF_DEFAULT_COMMAND='ag --nocolor --hidden --ignore .git -g ""'

# https://unix.stackexchange.com/a/33898
# Add our own directory to zsh's function search path:
fpath=( ~/.zfunc "${fpath[@]}" )

# Add `--no-use` to bring down exec time from 250ms to ~70ms
# https://github.com/nvm-sh/nvm/issues/782#issuecomment-588373363
# source /usr/share/nvm/init-nvm.sh --no-use

# expose python scripts of user-local python install:
export PATH=/home/fvdnabee/.local/bin:$PATH
